### ISSUE TITLE
create new AWS account for S3 free tier (new credit card)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/stream-to-s3#11]
My old account was **_deleted**_ without warning. 
Which is why I haven't used AWS for a while...

**Comment by nelsonic** [comment]
Obviously it didn't work...
https://console.aws.amazon.com/support/home?region=us-west-2#/case/?displayId=1486214301&language=en
![aws-phone-verifcation-system-fail](https://cloud.githubusercontent.com/assets/194400/9698953/42e94236-53c6-11e5-80aa-652156c9ec80.png)

**Comment by nelsonic** [comment]
![aws-support-account](https://cloud.githubusercontent.com/assets/194400/9698975/2ed7ed96-53c7-11e5-9e13-86a9536f88e9.png)

**Comment by nelsonic** [comment]
![aws-support-email](https://cloud.githubusercontent.com/assets/194400/9698983/8ce37608-53c7-11e5-98f9-35753a8d8a1c.png)

Don't you just _love_ it when systems automatically attach `Severity: Low` to your requests?

**Comment by nelsonic** [comment]
Pick up here: https://console.aws.amazon.com/support/home?region=us-west-2#/case/?displayId=1486214301&language=en

**Comment by iteles** [comment]
This is _exactly_ what happened to me in 2013 when I signed up, took 24 hours to fix via customer services emails.

**Comment by nelsonic** [comment]
Yeah, I will follow up on Monday. doubt they will bother to get back to me over the weekend...

**Comment by nelsonic** [comment]
Eventually got AWS to cooperate. :+1:
