### ISSUE TITLE
ask iteles for s3 keys

### ISSUE THREAD

**Issue by nelsonic** [dwyl/stream-to-s3#14]
@iteles do you have an _active_ AWS Account?

**Comment by iteles** [comment]
No such luck, mine also got deleted apparently (probably due to inactivity in the last year)

**Comment by nelsonic** [comment]
Closed?
As in you aren't going to _try_ and sign up again?

**Comment by iteles** [comment]
Yes, but I also didn't get past the phone verification https://github.com/nelsonic/stream-to-s3/issues/11#issuecomment-137943434 so you'll get one before me...!

**Comment by nelsonic** [comment]
Sounds like we need a _brand_ new bank account and a new "_test_" mobile phone number for dwyl AWS...

**Comment by iteles** [comment]
:+1:  That sounds like an issue worth opening... You or me?

**Comment by nelsonic** [comment]
I've created an AWS Account with ideaQ credit card for now. we can come back to this if/when we get a dwyl bank account. but for now its "sorted" :+1:

**Comment by iteles** [comment]
:+1: Excellent.
